
if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/CMakeUserPresets.json)
set(dynaplex_CMakeUserPresets_exists on)
else()
set(dynaplex_CMakeUserPresets_exists off)
endif()

if(${dynaplex_CMakeUserPresets_exists})
message("CMakeUserPresets detected in ${CMAKE_CURRENT_SOURCE_DIR}/CMakeUserPresets.json" )
else()
message("CMakeUserPresets not detected in ${CMAKE_CURRENT_SOURCE_DIR}/CMakeUserPresets.json")
message("Copying default userpresets")
configure_file("${CMAKE_CURRENT_SOURCE_DIR}/CMake/resources/CMakeUserPresets.json.in" ${CMAKE_CURRENT_SOURCE_DIR}/CMakeUserPresets.json)
endif()


message("inclusion switches (CMakeUserPresets.json):")
message("dynaplex_enable_pytorch: ${dynaplex_enable_pytorch}")
message("dynaplex_enable_gurobi: ${dynaplex_enable_gurobi}")

if(${dynaplex_enable_pytorch})	
find_package(Torch QUIET)
 if(Torch_FOUND)
 message(STATUS "Succesfully found Torch")
else()
 message(STATUS "Torch not found by dynaplex, even though it was requested via dynaplex_enable_pytorch flag. ") 
 message(STATUS "Please specify location of torch in CMAKE_PREFIX_PATH (for your current configuration) in CMakeUserPresets.json (*), or set dynaplex_enable_pytorch to FALSE ")
 message(STATUS "CMAKE_PREFIX_PATH:  ${CMAKE_PREFIX_PATH}")
 message(STATUS "(*) this file should be located in the DynaPlex folder, but might be invisible in some IDEs")
 find_package(Torch REQUIRED)
 message(FATAL_ERROR "Torch requested but not provided")
 endif()

else()
 message(STATUS "pytorch DISABLED : you will not be able to use neural networks. ") 
endif()
