#!/bin/bash
#SBATCH --time=00:10:00 --exclusive --nodes=1 --ntasks-per-node=1 --cpus-per-task=192 --partition genoa --mem=160G 
module load 2022
module load CMake/3.23.1-GCCcore-11.3.0
module load OpenMPI/4.1.4-GCC-11.3.0
export OMP_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1

cd ..
cmake --preset LinRel
cmake --build out/LinRel --target dcl_example -- -j 192

#cd ../out/LinRel/bin
#srun ./dcl_coll_picking

#cd ../python/test
#conda activate envDP
#srun python basics.py